
services:

  backend:
    image: ghcr.io/xyhelper/grok-share-server
    ports:
      - "8800:8001"
    environment:
      - TZ=Asia/Shanghai
      - GROKPROXY=
      - CALLBACKURL= #本服务回调地址
      - XYUCENTER=  #xyucenter（认证中心）部署地址
      - APPID= #子应用ID
      - APPJWTSECRETKEY= #子应用JWT token秘钥
    volumes:
      - ./backend/manifest:/app/manifest
      - ./config/config.yaml:/app/config.yaml
      - ./keywords.txt:/app/data/keywords.txt
    restart: unless-stopped

  mysql:
    image: mysql:8
    command: --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/mysql/:/var/lib/mysql/
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "cool"
      MYSQL_USER: "cool"
      MYSQL_PASSWORD: "123123"
    restart: unless-stopped

  redis:
    image: redis
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data/redis/:/data/
    restart: unless-stopped